version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ogame_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # <-- ЦЕЙ РЯДОК ОБОВ'ЯЗКОВИЙ. Він захищає Linux пакети від затирання з Windows.
    environment:
      - WATCHPACK_POLLING=true

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: ogame_gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/app
      - ./proto:/proto  # Maps the shared protocol buffers interface

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: ogame_core
    ports:
      - "50051:50051"
    volumes:
      - ./core:/app
      - ./proto:/proto # Maps the shared proto directory inside the container
