// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: game.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameService_ProcessAction_FullMethodName          = "/game.GameService/ProcessAction"
	GameService_GetServerTelemetry_FullMethodName     = "/game.GameService/GetServerTelemetry"
	GameService_GetDatabaseCatalog_FullMethodName     = "/game.GameService/GetDatabaseCatalog"
	GameService_SwitchOrCreateDatabase_FullMethodName = "/game.GameService/SwitchOrCreateDatabase"
	GameService_InitDatabaseSchema_FullMethodName     = "/game.GameService/InitDatabaseSchema"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	ProcessAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// New RPC for Phase 2 cluster health telemetry monitoring
	GetServerTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
	// Phase 4: Dynamic Database Management Cluster Routing
	GetDatabaseCatalog(ctx context.Context, in *DatabaseCatalogRequest, opts ...grpc.CallOption) (*DatabaseCatalogResponse, error)
	SwitchOrCreateDatabase(ctx context.Context, in *SwitchDatabaseRequest, opts ...grpc.CallOption) (*SwitchDatabaseResponse, error)
	InitDatabaseSchema(ctx context.Context, in *InitSchemaRequest, opts ...grpc.CallOption) (*InitSchemaResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) ProcessAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, GameService_ProcessAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetServerTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, GameService_GetServerTelemetry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetDatabaseCatalog(ctx context.Context, in *DatabaseCatalogRequest, opts ...grpc.CallOption) (*DatabaseCatalogResponse, error) {
	out := new(DatabaseCatalogResponse)
	err := c.cc.Invoke(ctx, GameService_GetDatabaseCatalog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SwitchOrCreateDatabase(ctx context.Context, in *SwitchDatabaseRequest, opts ...grpc.CallOption) (*SwitchDatabaseResponse, error) {
	out := new(SwitchDatabaseResponse)
	err := c.cc.Invoke(ctx, GameService_SwitchOrCreateDatabase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) InitDatabaseSchema(ctx context.Context, in *InitSchemaRequest, opts ...grpc.CallOption) (*InitSchemaResponse, error) {
	out := new(InitSchemaResponse)
	err := c.cc.Invoke(ctx, GameService_InitDatabaseSchema_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	ProcessAction(context.Context, *ActionRequest) (*ActionResponse, error)
	// New RPC for Phase 2 cluster health telemetry monitoring
	GetServerTelemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error)
	// Phase 4: Dynamic Database Management Cluster Routing
	GetDatabaseCatalog(context.Context, *DatabaseCatalogRequest) (*DatabaseCatalogResponse, error)
	SwitchOrCreateDatabase(context.Context, *SwitchDatabaseRequest) (*SwitchDatabaseResponse, error)
	InitDatabaseSchema(context.Context, *InitSchemaRequest) (*InitSchemaResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) ProcessAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessAction not implemented")
}
func (UnimplementedGameServiceServer) GetServerTelemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerTelemetry not implemented")
}
func (UnimplementedGameServiceServer) GetDatabaseCatalog(context.Context, *DatabaseCatalogRequest) (*DatabaseCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabaseCatalog not implemented")
}
func (UnimplementedGameServiceServer) SwitchOrCreateDatabase(context.Context, *SwitchDatabaseRequest) (*SwitchDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchOrCreateDatabase not implemented")
}
func (UnimplementedGameServiceServer) InitDatabaseSchema(context.Context, *InitSchemaRequest) (*InitSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDatabaseSchema not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_ProcessAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ProcessAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ProcessAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ProcessAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetServerTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetServerTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetServerTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetServerTelemetry(ctx, req.(*TelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetDatabaseCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetDatabaseCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetDatabaseCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetDatabaseCatalog(ctx, req.(*DatabaseCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SwitchOrCreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SwitchOrCreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_SwitchOrCreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SwitchOrCreateDatabase(ctx, req.(*SwitchDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_InitDatabaseSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).InitDatabaseSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_InitDatabaseSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).InitDatabaseSchema(ctx, req.(*InitSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessAction",
			Handler:    _GameService_ProcessAction_Handler,
		},
		{
			MethodName: "GetServerTelemetry",
			Handler:    _GameService_GetServerTelemetry_Handler,
		},
		{
			MethodName: "GetDatabaseCatalog",
			Handler:    _GameService_GetDatabaseCatalog_Handler,
		},
		{
			MethodName: "SwitchOrCreateDatabase",
			Handler:    _GameService_SwitchOrCreateDatabase_Handler,
		},
		{
			MethodName: "InitDatabaseSchema",
			Handler:    _GameService_InitDatabaseSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
