// core/src/main.rs
// Basic implementation of the Game Core gRPC server for Phase 1

use tonic::{transport::Server, Request, Response, Status};

// Import the auto-generated gRPC code modules
pub mod game {
    tonic::include_proto!("game"); // Matches the package name inside game.proto
}

use game::game_service_server::{GameService, GameServiceServer};
use game::{ActionRequest, ActionResponse};

// Define our server state structural object
#[derive(Debug, Default)]
pub struct MyGameService {}

// Implement the GameService trait generated by tonic-build
#[tonic::async_trait]
impl GameService for MyGameService {
    async fn process_action(
        &self,
        request: Request<ActionRequest>,
    ) -> Result<Response<ActionResponse>, Status> {
        // Extract the incoming data from the request package
        let req = request.into_inner();
        
        println!(
            "[Core] Received action request: '{}' with msg_id: '{}' from user_id: {}",
            req.action, req.msg_id, req.user_id
        );

        // Build a mock response mimicking successful execution
        let reply = ActionResponse {
            status: "processed".to_string(),
            msg_id: req.msg_id,
            payload: r#"{"message": "Hello from Rust bare-metal Core!"}"#.to_string(),
        };

        // Return the wrapped response back to the gRPC client
        Ok(Response::new(reply))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Define the network address where the gRPC server will listen
    // 0.0.0.0 allows internal Docker network communication on port 50051
    let addr = "0.0.0.0:50051".parse()?;
    let game_service = MyGameService::default();

    println!("[Core] gRPC Game Server listening on {}", addr);

    // Boot up the server architecture
    Server::builder()
        .add_service(GameServiceServer::new(game_service))
        .serve(addr)
        .await?;

    Ok(())
}
